name: Mon pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Installer les dépendances
        run: npm install

      - name: Exécuter les tests
        run: npm test

      - name: Construire l'image Docker
        run: docker build -t Calculatrice_DevOps .

      - name: Se connecter à Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pousser l'image Docker
        run: docker push Calculatrice_DevOps
